"use client";

import { useState } from "react";
import { Bar, BarChart, Cell, Radar, RadarChart, PolarAngleAxis, PolarGrid, ResponsiveContainer, XAxis, YAxis } from "recharts";
import { AlertTriangle, ArrowUpRight, BrainCircuit, CandlestickChart, Check, Gauge, Globe2, Leaf, Newspaper, ShieldAlert, SlidersHorizontal } from "lucide-react";
import Header from "./Header";
import AgentTerminal from "./AgentTerminal";

const baseLogs = ["[News Agent]: Processing 18 recent headlines. Net Sentiment: +0.62", "[Technical Agent]: MACD Bullish Crossover detected. RSI: 64.2", "[Risk Agent]: Computing Sharpe Ratio (1.82) and Volatility metrics...", "[Macro Agent]: Sector headwinds detected due to FED interest rate updates.", "[ESG Agent]: Environmental score: 85/100. Governance: Clean."];
const radar = [{ subject: "News", value: 82 }, { subject: "Technicals", value: 76 }, { subject: "Risk", value: 62 }, { subject: "Macro", value: 54 }, { subject: "ESG", value: 85 }];
const factors = [{ name: "Earnings", value: 25 }, { name: "Volatility", value: -10 }, { name: "Momentum", value: 15 }, { name: "Macro", value: -6 }];
const agents = [{ name: "News", icon: Newspaper, value: 24 }, { name: "Technicals", icon: CandlestickChart, value: 18 }, { name: "Risk", icon: ShieldAlert, value: 28 }, { name: "Macro", icon: Globe2, value: 14 }, { name: "ESG", icon: Leaf, value: 16 }];
const tabs = ["Technicals", "News stream", "Risk gauge", "Macro", "ESG breakdown"];

export default function Dashboard() {
  const [ticker, setTicker] = useState("NVDA"); const [auditing, setAuditing] = useState(false); const [weights, setWeights] = useState<Record<string, number>>({ News: 24, Technicals: 18, Risk: 28, Macro: 14, ESG: 16 }); const [tab, setTab] = useState("Technicals");
  function audit() { setAuditing(true); window.setTimeout(() => setAuditing(false), 2600); }
  return <main className="min-h-screen bg-[#0b0f17] text-slate-100"><Header ticker={ticker} onTickerChange={setTicker} isAuditing={auditing} onAudit={audit} />
    <div className="mx-auto max-w-[1800px] px-4 py-5 lg:px-7"><section className="panel mb-5 overflow-hidden"><div className="grid items-center gap-5 p-4 md:grid-cols-[1.2fr_.8fr_1.7fr] md:p-5"><div><p className="eyebrow">Portfolio decision / {ticker}</p><div className="mt-2 flex items-center gap-3"><span className="decision-pill">STRONG BUY</span><span className="font-mono text-xs text-emerald-300">+12.4% upside</span></div></div><div className="border-y border-slate-800 py-4 md:border-x md:border-y-0 md:px-6 md:py-0"><p className="eyebrow">Agent consensus score</p><div className="mt-2 flex items-end gap-3"><span className="font-mono text-4xl font-bold tracking-tight text-slate-50">78<span className="text-xl text-cyan-300">%</span></span><div className="mb-1 h-2 flex-1 overflow-hidden rounded-full bg-slate-800"><div className="h-full w-[78%] rounded-full bg-gradient-to-r from-cyan-400 to-emerald-400" /></div></div></div><div className="flex flex-wrap gap-2">{agents.map(({ name, icon: Icon }) => <div key={name} className="flex items-center gap-1.5 rounded-md border border-slate-800 bg-slate-900/60 px-2.5 py-2"><Icon size={13} className="text-cyan-300" /><span className="text-[11px] text-slate-300">{name}</span><Check size={12} className="text-emerald-400" /></div>)}</div></div></section>
      <div className="grid gap-5 xl:grid-cols-[.95fr_1.28fr_.9fr]"><div className="space-y-5"><AgentTerminal logs={baseLogs} isAuditing={auditing} /><section className="panel p-4"><div className="flex items-center justify-between"><div><p className="panel-title">Market pulse</p><p className="mt-1 text-xs text-slate-500">NASDAQ · delayed 15 min</p></div><ArrowUpRight className="text-emerald-400" size={20} /></div><div className="mt-4 flex items-end justify-between"><span className="font-mono text-2xl font-semibold">$182.41</span><span className="font-mono text-sm text-emerald-400">+4.22% today</span></div></section></div>
        <div className="space-y-5"><section className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-slate-800 px-4 py-3"><div className="flex items-center gap-2"><BrainCircuit size={16} className="text-cyan-300" /><h2 className="panel-title">XAI consensus matrix</h2></div><span className="tag tag-cyan">MODEL v4.2</span></div><div className="grid grid-cols-1 sm:grid-cols-2"><div className="border-b border-slate-800 p-3 sm:border-b-0 sm:border-r"><p className="chart-label">Agent confidence vector</p><ResponsiveContainer width="100%" height={220}><RadarChart data={radar} outerRadius="68%"><PolarGrid stroke="#334155" /><PolarAngleAxis dataKey="subject" tick={{ fill: "#94a3b8", fontSize: 10 }} /><Radar dataKey="value" stroke="#22d3ee" fill="#06b6d4" fillOpacity={0.26} /></RadarChart></ResponsiveContainer></div><div className="p-3"><p className="chart-label">Factor attribution</p><ResponsiveContainer width="100%" height={220}><BarChart data={factors} margin={{ top: 14, right: 0, left: -28 }}><XAxis dataKey="name" tick={{ fill: "#64748b", fontSize: 10 }} axisLine={false} tickLine={false} /><YAxis tick={{ fill: "#64748b", fontSize: 10 }} axisLine={false} tickLine={false} /><Bar dataKey="value" radius={[3,3,0,0]}>{factors.map((item) => <Cell key={item.name} fill={item.value > 0 ? "#10b981" : "#f43f5e"} />)}</Bar></BarChart></ResponsiveContainer></div></div><div className="m-3 rounded-lg border border-cyan-400/15 bg-cyan-400/[0.035] p-3.5"><p className="mb-2 font-mono text-[10px] font-bold uppercase tracking-[.13em] text-cyan-300">Explainable decision trace</p><p className="text-xs leading-5 text-slate-300"><span className="mr-2 text-emerald-400">↗</span>Positive earnings revision and momentum drive conviction. <span className="ml-2 mr-2 text-amber-400">!</span>Rate-sensitive growth exposure limits the score.</p></div></section>
          <section className="panel p-4"><div className="flex items-center gap-2"><AlertTriangle size={15} className="text-amber-400" /><h2 className="panel-title">Risk notes</h2></div><div className="mt-3 grid grid-cols-3 gap-2 text-center"><div className="metric"><b>1.82</b><span>Sharpe</span></div><div className="metric"><b className="text-amber-300">18.6%</b><span>Volatility</span></div><div className="metric"><b className="text-emerald-300">Low</b><span>Drawdown risk</span></div></div></section></div>
        <div className="space-y-5"><section className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-slate-800 px-4 py-3"><div className="flex items-center gap-2"><SlidersHorizontal size={15} className="text-cyan-300" /><h2 className="panel-title">Consensus weighting</h2></div><span className="font-mono text-[10px] text-slate-500">LIVE</span></div><div className="space-y-4 p-4">{agents.map(({ name }) => <label key={name} className="block"><div className="mb-1.5 flex justify-between text-xs"><span className="text-slate-300">{name} agent</span><span className="font-mono text-cyan-300">{weights[name]}%</span></div><input className="weight-slider" aria-label={`${name} weight`} type="range" min="0" max="50" value={weights[name]} onChange={(e) => setWeights({ ...weights, [name]: Number(e.target.value) })} style={{ "--value": `${weights[name] * 2}%` } as React.CSSProperties} /></label>)}</div></section>
          <section className="panel overflow-hidden"><div className="flex gap-1 overflow-x-auto border-b border-slate-800 p-2">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={`whitespace-nowrap rounded-md px-2.5 py-1.5 text-[11px] transition ${tab === item ? "bg-cyan-400/10 text-cyan-200" : "text-slate-500 hover:text-slate-300"}`}>{item}</button>)}</div><div className="p-4"><p className="eyebrow">{tab}</p><div className="mt-3 flex items-center justify-between"><div><p className="font-mono text-xl font-semibold text-slate-100">{tab === "Technicals" ? "BULLISH" : "ACTIVE"}</p><p className="mt-1 text-xs text-slate-500">Last refreshed 14 seconds ago</p></div><Gauge size={33} className="text-cyan-300" /></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full w-[76%] rounded-full bg-cyan-400" /></div></div></section></div></div></div></main>;
}
