"use client";

import { Activity, Command, Play, Search } from "lucide-react";

type HeaderProps = { ticker: string; onTickerChange: (ticker: string) => void; isAuditing: boolean; onAudit: () => void };
const tickers = ["AAPL", "NVDA", "TSLA", "BTC-USD"];

export default function Header({ ticker, onTickerChange, isAuditing, onAudit }: HeaderProps) {
  return <header className="border-b border-slate-800/80 bg-[#0b0f17]/90 px-5 py-3 backdrop-blur-xl lg:px-7"><div className="mx-auto flex max-w-[1800px] flex-col gap-3 xl:flex-row xl:items-center xl:justify-between"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-lg border border-cyan-400/30 bg-cyan-400/10 text-cyan-300 shadow-[0_0_22px_rgba(34,211,238,.13)]"><Activity size={18} strokeWidth={2.4} /></div><div><div className="font-mono text-lg font-bold tracking-[0.16em] text-slate-100">EMAFIS</div><div className="flex items-center gap-1.5 text-[10px] font-medium uppercase tracking-[0.13em] text-cyan-300"><span className="size-1.5 rounded-full bg-cyan-400 shadow-[0_0_8px_#22d3ee]" /> Multi-agent engine ready</div></div></div><div className="flex flex-1 flex-col gap-2 sm:flex-row xl:max-w-2xl"><label className="group flex h-10 min-w-0 flex-1 items-center gap-2 rounded-lg border border-slate-700/80 bg-slate-900/70 px-3 transition hover:border-slate-600 focus-within:border-cyan-500/60"><Search size={15} className="text-slate-500 group-focus-within:text-cyan-300" /><input aria-label="Search ticker" value={ticker} onChange={(e) => onTickerChange(e.target.value.toUpperCase())} className="min-w-0 flex-1 bg-transparent font-mono text-sm font-semibold tracking-wide text-slate-100 outline-none placeholder:text-slate-600" placeholder="Search ticker or asset" /><span className="hidden items-center gap-1 rounded border border-slate-700 bg-slate-800 px-1.5 py-0.5 font-mono text-[10px] text-slate-500 sm:flex"><Command size={10} />K</span></label><div className="flex items-center gap-1.5">{tickers.map((item) => <button key={item} onClick={() => onTickerChange(item)} className={`rounded-md border px-2 py-1.5 font-mono text-[11px] transition ${ticker === item ? "border-cyan-400/35 bg-cyan-400/10 text-cyan-200" : "border-slate-800 bg-slate-900/60 text-slate-400 hover:border-slate-700 hover:text-slate-200"}`}>{item}</button>)}</div></div><button onClick={onAudit} disabled={isAuditing} className={`flex h-10 items-center justify-center gap-2 rounded-lg px-4 text-xs font-bold uppercase tracking-[0.08em] transition ${isAuditing ? "border border-cyan-400/40 bg-cyan-400/20 text-cyan-100 shadow-[0_0_28px_rgba(34,211,238,.3)]" : "bg-cyan-400 text-slate-950 hover:bg-cyan-300 hover:shadow-[0_0_25px_rgba(34,211,238,.25)]"}`}>{isAuditing ? <span className="size-3 animate-spin rounded-full border-2 border-cyan-900 border-t-cyan-50" /> : <Play size={14} fill="currentColor" />}{isAuditing ? "Agents auditing" : "Run multi-agent audit"}</button></div></header>;
}
